name: dualgpuopt-ci
on: [push, pull_request]

# Explicitly restrict permissions
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        pyver: ["3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}
      - run: python -m pip install -r requirements.txt pytest
      - run: pytest -q
